# Generated by Django 6.0.5 on 2026-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='institucion_educativa',
            field=models.CharField(default='Pendiente', max_length=200),
            preserve_default=False,
        ),
    ]
